NYPL/research-catalog

pages/_document.tsx
https://jira.nypl.org/browse/SCC-3735
This PR moves the header placeholder style tags from the style.scss file to a style tag in the index.ejs file.
It also updates the styles according to the specifications in this document:
https://docs.google.com/document/d/1RjUXluYY9-MTYF5mzTI1GJmmykFtLrciM73f4gBGTvU/edit#heading=h.sgcc11v7s30d
=> SCC-3735 - Update header styles

.travis.yml, pages/search/index.tsx, src/models/SearchResultsBib.ts, src/types/bibTypes.ts, src/types/searchTypes.ts
This PR introduces the SearchResultsBib class, which handles the formatting and other utility functions for displaying search results. The majority of the logic is extracted from the ResultsList component in DFE.
The scope of this work does not include attributes pertaining to items or the items table in general, as this will be handled in a separate PR.
It also technically doesn't include the rendering of the Search Result data, although I've modified the temporary search results component to make use of the new SearchResultsBib model.
=> SCC-3713 - Search Results Bib model

src/components/Layout/Layout.tsx, src/components/RCLink/RCLink.tsx, src/components/SubNav/SubNav.tsx
Resolves JIRA Ticket [SCC-3899](https://jira.nypl.org/browse/SCC-3899)
- This updates the focus ring color for the links in the breadcrumbs and subnav to white for better color contrast.
=> SCC-3899: Focus ring accessibility fix

pages/search/advanced.tsx, src/components/SearchFilters/FieldsetDate.test.tsx, src/utils/advancedSearchUtils.ts
Resolves [SCC-3944](https://jira.nypl.org/browse/SCC-3944)
- Fixes mobile view for the form.
- Updates label headings to be consistent with current DFE.
=> SCC-3944: QA fixes on Advanced Search page

docker-compose.yml
Had to update this port number to match the dev environment for local development using docker.
=> SCC-3980 - Change port number in docker-compose

pages/index.tsx, src/config/config.ts
=> SCC-3990 - Remove main text and set reverseProxyEnabled to true on production

__test__/fixtures/searchResultsManyBibs.ts, src/components/RefineSearch/RefineSearch.test.tsx, src/components/RefineSearch/RefineSearchCheckboxField.tsx, src/models/SearchResultsFilters.ts
- add count to filter checkboxes
- transform greek language option
=> Scc 3704/refine results 2024 1 26

CHANGELOG
This PR adds release notes for the initial public release of the RC refactor.
=> SCC-4025 - Add 1.0 release notes

.travis.yml
This is a fix [proposed by devops](https://nypl.slack.com/archives/C1Q09LFAR/p1709306555084709) to fix the build errors we were encountering. Other teams have implemented this as well.
=> SCC-4025 - Add language and dist to travis config

pages/account/[[...index]].tsx, src/components/MyAccount/FeesBanner.tsx, src/components/MyAccount/FeesTab/FeesTab.test.tsx, src/components/MyAccount/FeesTab/FeesTab.tsx, src/components/MyAccount/ProfileTabs.tsx, src/models/MyAccount.ts, src/models/modelTests/MyAccount.test.ts, styles/components/MyAccount.module.scss
Resolves [SCC-3936](https://jira.nypl.org/browse/SCC-3936).
Adds Fees tab to My Account page.
=> SCC-3936: Fees tab

.husky/pre-push, jest.setup.js, package-lock.json, package.json, src/components/ItemFilters/ItemFilter.tsx, src/components/RCLink/RCLink.tsx, src/components/RefineSearch/RefineSearch.tsx, src/components/RefineSearch/RefineSearchCheckboxField.tsx, src/components/SearchFilters/AppliedFilters.tsx, src/components/SearchFilters/appliedFilterUtils.test.ts, src/components/SearchFilters/appliedFilterUtils.ts, src/types/filterTypes.ts, src/utils/itemFilterUtils.ts, src/utils/refineSearchUtils.ts
Updates TagSet implementation to use new v3 DS update. Not sure why the vercel deployment is failing...
=> Scc 4033/ds v3 update

src/models/MyAccount.ts, src/models/modelTests/MyAccount.test.ts
refactor logic to consolidate and remove nested if statements
=> Bib level holds if

CHANGELOG, src/components/Layout/Layout.test.tsx, src/components/SubNav/SubNav.test.tsx, src/components/SubNav/SubNav.tsx
=> SCC-4056 - Capitalize Out in Log Out link

README.md, accountREADME.md
Resolves [SCC-4019](https://jira.nypl.org/browse/SCC-4019).
Documents Sierra API endpoints for account page.
=> SCC-4019: Account API documentation

pages/search/index.tsx, src/components/DRB/DRBCard.tsx, src/components/DRB/DRBContainer.tsx, src/components/RCLink/RCLink.tsx, src/components/RefineSearch/RefineSearch.tsx, src/components/SearchForm/SearchForm.tsx, src/components/SearchResult/ElectronicResourcesLink.test.tsx, src/components/SearchResult/ElectronicResourcesLink.tsx, src/components/SearchResult/SearchResult.tsx, styles/components/Search.module.scss
Some more visual changes based on the last few items in the [VQA doc](https://docs.google.com/document/d/1qgHzrubMwxx_UvVu_hfVhDfbPEPPbgrypHv3BohSPtI/edit#heading=h.wq30kg5jzx41).
Specifically:
1. Search Results Card - Multiple Items + Available Online Links
2. DRB Sidebar
3. Pagination
4. Refine Search Dropdown
=> SCC-4066 - Search results VQA Pt. 2

CHANGELOG, __test__/pages/search/searchResults.test.tsx, pages/search/index.tsx, src/components/EDSLink.tsx, src/components/ItemTable/ItemAvailability.tsx, src/components/ItemTable/ItemTable.tsx, src/components/ItemTable/RequestButtons.tsx, src/components/Notification/Notification.tsx, src/components/RCLink/RCLink.tsx, src/components/RefineSearch/RefineSearch.tsx, src/components/SearchForm/SearchForm.tsx, src/components/SearchResult/ElectronicResourcesLink.tsx, src/components/SearchResult/SearchResult.tsx, src/utils/searchUtils.ts, src/utils/utilsTests/searchUtils.test.ts, styles/components/ItemTable.module.scss, styles/components/Search.module.scss
Resolves JIRA ticket [SCC-4065](https://jira.nypl.org/browse/SCC-4065)
Fixes VQA issues on the top half of the Search Results page, specifically for the headings in this [doc](https://docs.google.com/document/d/1qgHzrubMwxx_UvVu_hfVhDfbPEPPbgrypHv3BohSPtI/edit#heading=h.ia82i1lm88dj):
- Search Bar
- Results Heading and Sort Dropdown
- Search Results Card - Single Item
=> SCC-4065: Search Results VQA pt1

src/components/RefineSearch/RefineSearch.tsx, src/components/SearchForm/SearchForm.tsx, styles/components/Search.module.scss
Some small fixes that I wanted to get in before the second round of VQA. Noticed the Advanced search link was no longer on the left so I added a margin: left style.
Also removed a console log in passing and nudged the advanced search link up with a negative margin per Apoorva's comment in the Search Bar section of the VQA doc.
=> SCC-4066 - Small VQA fixes

src/server/api/bib.ts, src/server/api/drb.ts, src/server/kms.ts, src/server/sierraClient/index.ts
Missed some of the serverside logs in [original logging PR](https://github.com/NYPL/research-catalog/pull/176) so just adding them here.
=> SCC-4010: FIX Moving all serverside logs to logger

.github/pull_request_template.md
- Adding the generic Github PR template already used in the DS and Digital Collections.
=> Github PR Template

package-lock.json
- Merges main into QA in anticipation of the Search Results page release on 5/9/24.
=> Merge main into qa

CHANGELOG
- Adds notes to the Changelog pertaining to the public release of the Search Results page. (v1.0.0).
=> v1.0.0 Changelog Release Notes

src/components/SearchFilters/appliedFilterUtils.ts
This is a stopgap for https://jira.nypl.org/browse/SCC-4118. it may in fact solve the problem, as discovery api is expected to sometimes not return aggregations for query parameters in combination.
=> Hotfix applied filters vk

__test__/pages/Home.test.tsx, src/components/Layout/Layout.test.tsx, src/components/Layout/Layout.tsx, src/components/SubNav/SubNav.test.tsx, src/components/SubNav/SubNav.tsx
We will be temporarily removing the Account link from the subnav while we resolve an issue preventing users from logging in.
=> HOTFIX - Remove my account link

src/components/Layout/Layout.tsx
Updating the copy in the notification banner to reflect search not working.
=> HOTFIX - Update notifcation banner

CHANGELOG, src/utils/searchUtils.ts, src/utils/utilsTests/searchUtils.test.ts
Relevant PRs / tickets:
https://github.com/NYPL/research-catalog/pull/221
https://jira.nypl.org/browse/SCC-4137
=> Backsync Advanced Query clearing bug hotfix from production to qa

src/components/MyAccount/RequestsTab/CancelButton.tsx, src/components/MyAccount/RequestsTab/FreezeButton.tsx, styles/components/MyAccount.module.scss
- JIRA ticket [SCC-4161](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4161)
- update hold freeze modal copy
- adjust cancel request modal spacing
- top align table headers
- the ticket also called out not seeing the cancel confirmed modal, but I'm seeing it, so I didn't fix anything there.
locally
-
=> vqa requests tab

src/components/MyAccount/Settings/AccountSettingsDisplayOptions.tsx, src/components/MyAccount/Settings/AccountSettingsUtils.test.ts, src/components/MyAccount/Settings/AccountSettingsUtils.ts, src/components/MyAccount/Settings/PasswordModal.tsx, styles/components/MyAccount.module.scss
- JIRA ticket [SCC-4162](https://newyorkpubliclibrary.atlassian.net/jira/software/c/projects/SCC/boards/126?assignee=61e836e95fcc37006878c15d&selectedIssue=SCC-4162)
-    adds dashes to the phone number display
-    move update pin/password button
-    align pin password modal body with heading
-    Ensure the edit/save/cancel buttons move to the bottom of the tab on mobile view
-
=> Scc 4162/vqa account settings

src/components/MyAccount/RequestsTab/RequestsTab.tsx, src/components/MyAccount/RequestsTab/UpdateLocation.tsx, styles/components/MyAccount.module.scss
- JIRA ticket [SCC-4165](https://newyorkpubliclibrary.atlassian.net/jira/software/c/projects/SCC/boards/126?assignee=61e836e95fcc37006878c15d&selectedIssue=SCC-4165)
for mobile view:
- wraps text of status badge
- stacks manage requests buttons vertically
- make change location button smaller
visually
- NA
=> Scc 4165/vqa2 requests mobile

pages/account/[[...index]].tsx, src/components/MyAccount/TimedLogoutModal.tsx, src/utils/cookieUtils.ts, src/utils/utilsTests/cookieUtils.test.ts
Re-fix the bug! Which was another hidden bug... Off by one 🫠
=> Noref logout modal 6 24

src/server/auth.ts
=> use https for login redirect

pages/account/[[...index]].tsx, src/components/MyAccount/Settings/AccountSettingsUtils.ts, src/server/auth.ts, src/utils/myAccountUtils.ts
https://nypl.slack.com/files/U04TFQGQFTQ/F07GS083E7J/image.png
addressing this error which appeared in prod. it was happening due to a notification preference that was null.
also adds error handling to the entire return statement of my account page.
=> account settings bug and error handling

src/models/MyAccount.ts, src/models/modelTests/MyAccount.test.ts
hold status `b` should equate to a `READY FOR PICKUP` status label
=> add status b 

CHANGELOG, package.json, pages/account/[[...index]].tsx, src/components/MyAccount/Settings/AccountSettingsUtils.ts, src/components/MyAccount/TimedLogoutModal.tsx, src/models/MyAccount.ts, src/models/modelTests/MyAccount.test.ts, src/server/auth.ts, src/server/tests/auth.test.ts, src/utils/myAccountUtils.ts
- JIRA ticket [SCC-4221](https://newyorkpubliclibrary.atlassian.net/jira/software/c/projects/SCC/boards/126?assignee=61e836e95fcc37006878c15d&selectedIssue=SCC-4221)
[SCC-4221]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> timeout modal fix

CHANGELOG, src/components/EDSLink.tsx
- JIRA ticket [SCC-4226](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4226)
- Updates ebsco link url
[SCC-4226]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCC-4226 - Update Ebsco link url

CHANGELOG, __test__/pages/test-pickup-times/index.test.tsx, package-lock.json, package.json, src/components/Layout/Layout.test.tsx, src/components/SearchForm/SearchForm.test.tsx, src/components/SearchForm/SearchForm.tsx, src/config/constants.ts, src/utils/searchUtils.ts, styles/components/Search.module.scss
- JIRA ticket [SCC-4623](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4263)
- add search tips to search bar per search scope option
- this seems like something that we would definitely want someone using a screen reader to be able to hear. how do we ensure that happens?
=> add search tips

src/components/ItemTable/ItemTableControls.tsx, styles/components/ItemTable.module.scss
- JIRA ticket [SCC-4264](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4264)
- Minor styling changes
[SCC-4264]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCC-4264 - VQA third pass fixes

CHANGELOG, src/components/SearchForm/SearchForm.test.tsx, src/components/SearchForm/SearchForm.tsx, src/config/constants.ts
- Comments out search tip additions and replaces label text to match production.
=> rollback search form updates

src/config/constants.ts
reverts drop down to original state, including order and labels.
=> revert dropdown order and label

CHANGELOG, package.json, src/components/ItemTable/ItemTable.tsx, src/components/SearchResults/ElectronicResourcesLink.tsx, src/components/SearchResults/SearchResult.tsx, styles/components/ItemTable.module.scss
- JIRA ticket [SCC-4299](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4299)
- Styling changes (mostly related to DS table updates) requested by Apoorva following the Bib page launch
Apoorva VQA'd the vercel link and approved
NA
[SCC-4299]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCC-4299 - Design approved styling fixes post DS Table updates

CHANGELOG, src/config/constants.ts
=> Scc 4260/rename fields

CHANGELOG, src/components/EDSBanner.tsx, src/components/Layout/Layout.tsx
Move eds banner out of logical render
=> Hotfix changes

src/components/Layout/Layout.tsx, src/components/SearchForm/SearchForm.tsx
- update icon
- only show banners on search
=> Scc 4260/vqa final updates

src/components/EDSBanner.tsx
=> update eds link

src/components/MyAccount/Settings/SettingsSelectForm.tsx
Missed this commit when I merged into main
=> Pulling out type = notification

CHANGELOG, src/server/nyplApiClient/index.ts
Paul found a memory issue due to this cache being WACKY! 
- Updated the client cache be an object, 
- update cache setter with keys that match what we are querying the cache for!
=> Fix nonsense cache

CHANGELOG, pages/_app.tsx
- JIRA ticket [SCC-4536](https://newyorkpubliclibrary.atlassian.net/browse/SCC-SCC-4536)
- This PR adds the OptinMonster snippet as requested by the comms team to support a marketing campain.
NA
NA
[SCC-4536]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCC-4536- Add Optinmonster snippet

CHANGELOG, pages/_app.tsx, pages/_document.tsx
- JIRA ticket [SCC-4472](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4472)
- Temporarily remove GTM code for renewals update deployment
[SCC-4472]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCC-4472 - Temporarily remove GTM code

CHANGELOG, pages/_app.tsx, pages/_document.tsx
- I had temporarily removed this due to a production push earlier. I'm restoring it now so we can test it on QA.
=> SCC-4472 - Restore GTM Snippet after deployment

src/server/api/hold.ts, src/types/holdPageTypes.ts
What the title says! Regression in hold flow crept in with my last update.
=> replace recordtype in holds

__test__/fixtures/rawSierraAccountData.ts, src/models/MyAccount.ts, src/types/myAccountTypes.ts
Fix regression from over-replacing `recordType` with `format`
=> Scc 4417/format filters

CHANGELOG, package-lock.json, package.json, src/components/DRB/DRBCard.tsx, src/components/DRB/DRBContainer.tsx, src/components/ItemFilters/ItemFilters.test.tsx, src/components/ItemTable/ItemAvailability/ContactALibrarian.tsx, src/components/RefineSearch/RefineSearch.test.tsx
- JIRA ticket [SCC-4630](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4630)
- Updates to DS version `3.6.1` which mainly changes font weights
- Corrects some tests
[SCC-4630]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCC-4630: Update to DS v3.6.1

src/components/SearchForm/SearchForm.tsx, src/models/BibDetails.ts, src/server/api/bib.ts
- JIRA ticket [xxx](https://newyorkpubliclibrary.atlassian.net/browse/SCC-{fill in the ticket number})
-
-
=> reset shep redirect

pages/search/index.tsx, src/components/AppliedFilters/AppliedFilters.tsx, src/components/SearchFilters/SearchFilterModal.tsx, src/components/SearchFilters/SearchFilters.tsx, src/components/SearchForm/SearchForm.tsx, src/context/FocusContext.tsx
- refactor some focus
- refactor checkbox change handler
=> Merge changes to QA

src/components/BibPage/ElectronicResources.tsx, src/components/MyAccount/ProfileHeader.tsx, src/components/SearchFilters/SearchFilterModal.tsx, src/components/SearchForm/SearchForm.test.tsx, src/components/SearchForm/SearchForm.tsx, src/context/FocusContext.tsx
I believe the focus was getting lost somewhere in the chakra modal focus handling. To ameliorate, i propose using the built-in focus handling, which automatically focuses on the button that triggered the modal to open. This PR refactors the filters modal to use some more chakra hooks.
=> use chakra modal focus handling

CHANGELOG, package-lock.json, package.json, playwright/pages/base_page.ts, playwright/pages/rc_home_page.ts, playwright/tests/Homepage/homepage.spec.ts, playwright/tests/example.spec.ts, src/components/BibPage/FindingAid.test.tsx, src/components/BibPage/FindingAid.tsx, src/models/Bib.ts, src/models/BibDetails.ts, src/models/modelTests/BibDetails.test.ts, src/types/bibTypes.ts
- Updated finding aid copy and link [SCC-4803](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4803)
- Added Playwright tests for RC home page elements. found in /playwright. Deleted dummy test file that was created for initial Playwright install. [SCC-4792](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4792)
- Added Playwright, the end-to-end testing framework for automating and verifying browser interactions across Chromium, Firefox, and WebKit. [SCC-4772](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4772)
- Trailing period removal from subject literals [SCC-4801](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4801)
[SCC-4803]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> Release 1.5.2

CHANGELOG, __test__/fixtures/processedMyAccountData.ts, src/components/MyAccount/RequestsTab/CancelButton.tsx, src/components/MyAccount/RequestsTab/RequestsTab.test.tsx, src/models/MyAccount.ts, src/types/myAccountTypes.ts
- JIRA ticket [SCC-4807](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4807)
- Add logs on successful and failed hold cancellations
-
[SCC-4807]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add log to cancel button

CHANGELOG, __test__/fixtures/processedMyAccountData.ts, package-lock.json, package.json, pages/index.tsx, src/components/MyAccount/RequestsTab/CancelButton.tsx, src/components/MyAccount/RequestsTab/RequestsTab.test.tsx, src/models/MyAccount.ts, src/types/myAccountTypes.ts
- Logs on hold cancel button [SCC-4807] (https://newyorkpubliclibrary.atlassian.net/browse/SCC-4807)
- Fixed broken homepage "Locations" link [SCC-4837](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4837)
[SCC-4807]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCC-4837]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release 1.5.3

package-lock.json
- JIRA ticket [xxx](https://newyorkpubliclibrary.atlassian.net/browse/SCC-{fill in the ticket number})
-
-
=> Take 2 1.5.5
