NYPL/research-catalog

.travis.yml
README.md
package.json
pages/404.tsx
pages/404/index.tsx
pages/404/redirect.tsx
src/components/Layout/Layout.tsx
src/config/constants.ts
src/types/pageTypes.ts
src/utils/appUtils.ts

This PR adds the 404 page template and logic to hide the Research Catalog header on 404 pages.
Unrelated to the ticket, but I also changed the localhost port to 8080 temporarily to avoid conflicts with port 3000 on DFE for convenience.
https://jira.nypl.org/browse/SCC-3618

SCC-3618 - 404 page

---

.travis.yml
Dockerfile
ENVIRONMENTVARS.md
package.json
pages/_document.tsx

It seems the travis var name was not consistent with what docker and the app expected the env var to be so the Header and Footer never loaded in the AWS QA instance. This should fix that.

Header URL env var update

---

pages/index.tsx

Small update to get relative urls for NYPL.org links. This is to get the appropriate QA or production link for testing.
I could not use the `RCLink` component since next.js thinks a relative link is part of the app and injects the root URL. So instead just the DS `Link` is used so that the URL is relative to the domain and not the root path (/research/research-catalog).
This won't work locally or on Vercel but _should_ work on the QA site _after_ we do the reverse proxy. For example, 
`https://qa-research-catalog.nypl.org/about/divisions` won't work but when the app is reverse proxied onto qa-www.nypl.org, it'll work as intended.

Homepage relative urls

---

__test__/pages/404/404.test.tsx
__test__/pages/Home.test.tsx
__test__/pages/search/advancedSearchForm.test.tsx
__test__/pages/search/searchResults.test.tsx
next.config.js

Removing `pageExtension` from nextjs' config. It did not allow the render locally or on Vercel.

Removing nextjs config for page routing

---

pages/search/index.tsx
src/components/SearchForm/SearchForm.test.tsx
src/components/SearchForm/SearchForm.tsx

- Search form prepopulates search bar with the value of q from the url (not global state). 
- Select and text input are now controlled components sharing a handler function
- tests!
- also updated search results string to be dynamic to less than 50 results

Make search form controlled component

---

__test__/fixtures/searchResultElectronicResources.ts
__test__/fixtures/searchResultPhysicalItems.ts
__test__/pages/search/searchResults.test.tsx
pages/search/index.tsx
src/components/SearchResult/SearchResult.test.tsx
src/components/SearchResult/SearchResult.tsx
src/config/constants.ts

This PR initializes the Search Result component as well as basic tests for rendering the primary Bib fields.
https://jira.nypl.org/browse/SCC-3714
It does not include fields or other functionality related to the item table.

SCC-3714 - Search Results Component

---

CHANGELOG
package-lock.json
pages/index.tsx
src/components/RCLink/RCLink.tsx
src/components/SearchForm/SearchForm.tsx
src/components/SubNav/SubNav.test.tsx
src/components/SubNav/SubNav.tsx
styles/components/Search.module.scss

Fixes Ticket [SCC-2839](https://jira.nypl.org/browse/SCC-3829)
- Adds the `aria-current="page"` attribute to the `SubNav` component for the link on the active page.
- Sets the "Advanced Search" link to `ui.link.secondary` color for better color contrast. Will check this with @bigfishdesign13.
- Adds an aria-label to the "Learn more" link.
- Removes redundant "Image of" text in image alt text.
Additionally, added a `CHANGELOG.md` file.
Vercel Link: https://research-catalog-git-scc-2839-homepage-a11y-updates-nypl.vercel.app/research/research-catalog

SCC-2839: Homepage a11y updates

---

src/components/EDSLink.tsx
src/components/RCLink/RCLink.tsx
src/components/SearchForm/SearchForm.test.tsx
src/components/SearchForm/SearchForm.tsx
src/config/constants.ts
styles/components/Search.module.scss
styles/components/SubNav.module.scss

This combines work called out in 3 VQA tickets (SCC-3830, 3831, and 3832), including:
-  Page title change to “Research Catalog | NYPL”.  
-  Add Article Search link
- SubNav wrapping keeping link text together
- Note this one i did not follow the spec 100%, but instead implemented a simpler fix... TBD if it is acceptable.
- Placeholder text in the text input field italicized.
- An ‘X’ clear button should appear in the text input field once the patron starts typing - I believe this functionality exists in the DS search bar, but let me know if that isn’t the case. 
- this and previous was fixed with my search form update to include the DS search bar
- 16px margin for Advanced Search button

SCC-383x/vqa

---

__test__/fixtures/searchResultElectronicResources.ts
pages/search/advanced.tsx
src/components/DRB/DRBCard.tsx
src/components/RCLink/RCLink.tsx
src/components/SearchResult/ElectronicResourcesLink.test.tsx
src/components/SearchResult/ElectronicResourcesLink.tsx
src/components/SearchResult/SearchResult.tsx
src/models/SearchResultsBib.ts
src/types/bibTypes.ts

Ticket: https://jira.nypl.org/browse/SCC-3897
This PR adds the ElectronicResourcesLink component that is mostly derived from the ElectronicResourcesResultsItem component in DFE, with a few minor adjustments.

SCC-3897 - Search Results Electronic Resources Link

---

__test__/pages/search/advancedSearchForm.test.tsx
package-lock.json
package.json
pages/search/advanced.tsx

Resolves JIRA ticket [SCC-3904](https://jira.nypl.org/browse/SCC-3904).
This fixes six main issues found on the Advanced Search page:
- Removes the `DatePicker` component for text input components. Accessibility issues were flagged in the `DatePicker` and the DS team wants to take a step back to fix them. So it's not a blocker, the `TextInput` component should be used for now.
- Adds focus to the error message when it is rendered.
- Updates the error messages to include the work "Error: ..."
- Adds a basic validation so that the "From" date cannot be bigger than the "To" date.
- Updates the button group layout for the Clear and Submit button.
- Moves the date fields to the first column for better visual layout.

SCC-3904: Advanced Search page A11y and VQA fixes

---

vercel.json

This PR adds a simple redirect to vercel.json that automatically redirects to the base url /research/research-catalog.
It seems to be working in the preview link of this PR, so I'm hoping this is sufficient to get all vercel works to redirect correctly.

Scc 3972/add redirect to vercel json

---

src/components/BibPage/BibDetail.test.tsx
src/models/BibDetails.ts
src/models/modelTests/BibDetails.test.ts

Unit tests were failing on `main` because of Nextjs vs DS `Link` component usage. The Nextjs `Link` component was removed (but will be added later) and that broke some tests which (somehow) did not fail before.
This also encodes the query param values same as they are in prod.

Fixing nextjs/DS Link unit test failures

---

pages/api/search.ts
pages/search/advanced.tsx
pages/search/index.tsx
src/utils/searchUtils.ts
src/utils/utilsTests/searchUtils.test.ts
vercel.json

This PR fixes an issue where an empty search would yield no results.
This was caused by the query string falling back to "" instead of "?" when search params are absent. I also set a default q value of "" when it is undefined so that it displays as the search term instead of "undefined".

SCC-3838 - Fix empty search query

---

__test__/pages/404/404.test.tsx
package-lock.json
pages/404/index.tsx
pages/404/redirect.tsx
src/components/SearchResult/ElectronicResourcesLink.test.tsx
src/components/SearchResult/ElectronicResourcesLink.tsx
src/components/SearchResult/SearchResult.test.tsx
src/components/SearchResult/SearchResult.tsx
src/components/SubNav/SubNav.tsx

Several links on the refactored app were broken after the change to the DS Link component that renders a basic link rather than a next link, which automatically prepended the base url.
This PR simply adds the base URL to the links that were missing it and fixes the failing tests.

SCC-3987 - Add base URL to links and update tests

---

src/components/FeedbackForm/FeedbackForm.tsx

Small fix that shows the user an error when there's an issue in the feedback API endpoint response, most likely an error returned from the SES service.

SCC-3614 - Show error to user when there is an error on in the feedback api response

---

CHANGELOG
pages/search/advanced.tsx

Small bug fix, passing req instead of req.cookies to initializePatronTokenAuth was preventing the authentication status from being set correctly on advanced search.

SCC-4028 - Pass req.cookies into initializePatronTokenAuth

---

pages/search/index.tsx
src/components/RefineSearch/RefineSearch.test.tsx
src/components/RefineSearch/RefineSearch.tsx
src/components/SearchFilters/AppliedFilters.test.tsx
src/components/SearchFilters/AppliedFilters.tsx
src/components/SearchFilters/FieldsetDate.tsx
src/components/SearchForm/SearchForm.tsx
src/server/auth.ts
src/types/drbTypes.ts
src/types/filterTypes.ts
src/types/searchTypes.ts
src/utils/refineSearchUtils.ts
src/utils/utilsTests/refineSearchUtils.test.ts
styles/components/Search.module.scss

This PR incorporates the date fields into the refine search dialog and the filter tag set. 
- The date fields, when inputs are provided and the refine search filters are applied, populate the url query params. 
- Those applied filters, including the dates, populate the filter tag set in the search results view. 
- A url with date params set will populate the date fields of the refine search filters

Scc 4027/add dates 2

---

__test__/pages/search/searchResults.test.tsx
pages/search/index.tsx
src/components/RefineSearch/RefineSearch.tsx
src/utils/searchUtils.ts
src/utils/utilsTests/searchUtils.test.ts

Includes advanced search params to "Displaying 1-50 results..." string so users know what advanced search params have been applied to their search. Advanced search options that are filters are not included in this, but they do show up in the applied filters tagset.

Scc 4027/adv search display

---

src/utils/itemUtils.ts

items with status:o/use in library are not requestable in Sierra due to loan rules. They should not be considered available on the front end, either.

rm status:o from available criteria

---

__test__/fixtures/myAccountFixtures.js
src/components/MyAccount/FeesBanner.tsx
src/components/MyAccount/ItemsTab.tsx
src/config/config.ts
src/models/MyAccount.ts
src/models/modelTests/MyAccount.test.ts
src/server/api/bib.ts
src/server/api/tests/bib.test.ts

Ticket:
https://jira.nypl.org/browse/SCC-4062
In anticipation of the changing of the vega url from https://nypl.na2.iiivega.com to borrow.nypl.org, I'm opening a small PR that replaces any hardcoded instance of the old url with the value stored in appConfig to easily switch it over.
All instances of the url in DFE are currently coming from an Env var so it should just be a matter of changing it and redeploying there when it's time to switch.

SCC-4062 - Replace hardcoded vega links with config var

---

.travis.yml

travis builds werent correctly tagging the previous QA and prod images -- 
```
aws: error: argument --image-tag: expected one argument
The command "MANIFEST=$(aws ecr batch-get-image --repository-name research-catalog --image-ids imageTag="$ENV-latest" --output json | jq --raw-output --join-output '.images[0].imageManifest')
```
the `$ENV` var was removed in favor of `$NEXT_PUBLIC_APP_ENV`
tested here: https://app.travis-ci.com/github/NYPL/research-catalog/builds/269946130
CC @gkallenberg 
ticket on SEB board - https://jira.nypl.org/browse/SEB-3102

[SEB-3102] fix env var for travis previous image tagging

---

__test__/pages/Home.test.tsx
__test__/pages/search/searchResults.test.tsx
pages/search/index.tsx
src/components/Layout/Layout.test.tsx
src/components/Layout/Layout.tsx
src/components/MyAccount/RequestsTab/CancelButton.tsx
src/components/RefineSearch/RefineSearch.test.tsx
src/components/RefineSearch/RefineSearch.tsx
src/components/RefineSearch/RefineSearchCheckboxField.tsx
src/components/SearchFilters/AppliedFilters.test.tsx
src/components/SearchFilters/AppliedFilters.tsx
src/components/SearchForm/SearchForm.test.tsx
src/components/SearchForm/SearchForm.tsx
src/context/SearchResultsAggregationsContext.tsx
src/utils/searchUtils.ts
src/utils/utilsTests/searchUtils.test.ts
styles/utils/a11y.module.scss

Addresses [this ticket](https://jira.nypl.org/browse/SCC-4063)
- focus updates
- opening refine search should focus on cancel, clicking cancel should focus on refine search button
- applying filters, clearing filters, removing filters from the tagset focus on "Displaying n results..." heading
- sorting results should return focus to sort by selector
- refine checkboxes layout
- checkboxes switch to rows of 2 on mobile view, text does not overlap with checkboxes
- there was also a note about updating colors, but it looks like that will be happening DS-side
In order to make the focus work simpler, I refactored the search page. Instead of rendering the layout and the layout decides when and where to render the search form, the search form is generated on the search page and then passed into …

Scc 4063/search results vqa

---

src/utils/refineSearchUtils.ts
src/utils/utilsTests/refineSearchUtils.test.ts

this endpoint:
`https://qa-www.nypl.org/research/research-catalog/search?q=dance&filters[holdingLocation][0]=loc:scff2`
Though it is technically not supported by the front end, I use it for QA and finding bibs with specific holding locations. It was causing a server error. I added some extra checks to make sure that filters not present in aggregations do not break the site.

Noref location filter bugfix

---

src/components/ItemTable/RequestButtons.test.tsx
src/components/ItemTable/RequestButtons.tsx
src/components/SearchResult/SearchResult.tsx

Adds `BASE_URL` to the hold request links.
- The Hold pages don't exist in this app yet, so the route will return a 404.
- In the context of the QA site that has reverse proxy, this update will navigate from Research Catalog search results to Discovery Front-End Hold pages.

Adding base URL to hold request links

---

.gitignore
README.md
__test__/mocks/logger.js
logger.js
package-lock.json
package.json
pages/account/[[...index]].tsx
pages/index.tsx

Resolves ticket [SCC-4010](https://jira.nypl.org/browse/SCC-4010).
- Adds [Winston](https://www.npmjs.com/package/winston) logging package and sets up NYPL logging standards. 
- Adds mock logger (which is not necessary yet but will be once we write a11y testing for pages)
- Adds a section in the README for logging
- Changes all logs in `getServerSideProps` to use the logger
- Cleans up logs a little bit– we don't need to log the patron authentication token on the homepage, and probably not on the account page either (I'll remove it once My Account work phase 1 is done)
Test by running the app locally and clicking My Account. You should see a info-level log of the patron authentication token in the terminal.
This should automatically work in AWS Cloudwatch but may need another PR to …

SCC-4010: Logging for Cloudwatch

---

src/components/DRB/DRBCard.tsx
src/components/DRB/DRBContainer.tsx
src/utils/drbUtils.ts
src/utils/utilsTests/drbUtils.test.ts

Ticket:
https://jira.nypl.org/browse/SCC-4094
Turns out the search scope (aka "field") wasn't being mapped to the DRB equivalent on Research Catalog, as it is on Discovery Front End via the mapSearchScope map.

SCC-4094 - DRB results not appearing on author searches

---

CHANGELOG
src/components/SearchForm/SearchForm.tsx
src/utils/searchUtils.ts
src/utils/utilsTests/searchUtils.test.ts

- JIRA ticket [SCC-4093](https://jira.nypl.org/browse/SCC-4093)
- "subject" searches should go to SHEP.
- Bug that Chris found in an existing ticket so this is subsequent work.
Locally, this will not work because SHEP does not exist. This will work, however, in the reverse proxy state.
- N/A

SCC-4093 update: Making subject searches going to SHEP

---

CHANGELOG
__test__/fixtures/itemFixtures.ts
src/models/modelTests/Item.test.ts
src/utils/itemUtils.ts

- JIRA ticket [SCC-4123](https://jira.nypl.org/browse/SCC-4123)
- Adds "status:o" (Use in Library) to the Availability Ids list used to generated Availability text.
- Removes a couple of unused item fixtures (itemNoShelfMark and itemNoShelfMarkNoURI) but I can add them back if they'll be useful later.

Item Availability Bug

---

src/components/MyAccount/CheckoutsTab/RenewButton.tsx

No ticket, this fix will be duplicated in #213
- Adds onClose to renew checkout success/failure modals
Locally

Bug: Closing renew checkout modal

---

CHANGELOG
src/server/api/search.ts

Error: search page returned a 500 error
This fix catches the API call error and display a "No results. Try a different Search" message but still renders the page.
--- 
Platform API calls were invoked in the `promise.allSettled` too soon. This handles the issue where Platform API is down and calls to the `NyplApiClient` cannot be made.
Specifically, `nypl-data-api-client` threw an error failing to get a token:

Hotfix: catching Platform API errors

---

CHANGELOG
src/components/MyAccount/ProfileTabs.tsx

- JIRA ticket [SCC-4130](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4130)
- Constraints the width of the `Tabs` component on mobile only. I was looking at updating the `Table` component itself but because it will go through some updates in the next few weeks, and because the issue is more global, I worked on the `Tabs` instead.
Before
After
Locally. Zoom in at 400x and view the checkouts table. It's not a perfect solution though so it may need a few tweaks.
- Needs another accessibility review.

SCC-4130: My Account - checkouts table accessibility zoom fix

---

src/components/EDSLink.tsx
src/components/MyAccount/ProfileHeader.tsx
src/components/MyAccount/ProfileTabs.tsx
src/components/MyAccount/RequestsTab/RequestsTab.tsx
src/components/MyAccount/RequestsTab/UpdateLocation.test.tsx
src/components/MyAccount/RequestsTab/UpdateLocation.tsx
src/components/SubNav/SubNav.tsx

- JIRA ticket [SCC-4160](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4160)
- Adds the white focus outline on the "Log out" link.
- Makes the barcode's width smaller on mobile so that the parent element and layout is more responsive. This causes a minor flicker for the barcode when it renders but let me know if it's jarring @charmingduchess .
- Adds `aria-label` to the "Change location" button. This meant passing the entire `hold` rather than `holdId` to the `UpdateLocation` component.
- Still need to work on one issue that is waiting for Clare's clarification.
Locally.
- Fixes a few issues found by Clare during her review.

SCC-4160: Second pass of accessibility fixes for My Account

---

pages/bib/[id]/index.tsx

This is a simple renaming to allow for cleaner diff in the View All items PR.

Rename bib page index file from [id].tsx to index.tsx

---

CHANGELOG
src/components/MyAccount/Settings/AccountSettingsUtils.test.ts
src/utils/myAccountUtils.ts

- JIRA ticket [SCC-4175](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4175)
- Fixes a bug parsing the patron name when a non-comma separated value is passed, as was seen on Chris' test account.
- Added unit tests for formatPatronName
- We should look into why the account name wasn't received in the Sierra format and whether this will impact non-test accounts.
[SCC-4175]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4175 - Fix patron name parsing issue

---

CHANGELOG
__test__/pages/bib/bibPage.test.tsx
src/components/BibPage/BibDetail.test.tsx
src/components/BibPage/BibDetail.tsx

- JIRA ticket [SCC-4150](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4150)
- Uses lodash's kebabCase method to convert the test ids used in bibDetails to conform to the format used elsewhere in the app.
- I've updated the unit tests
NA
[SCC-4150]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4150 - Convert bib detail ids to kebab case

---

src/components/MyAccount/CheckoutsTab/CheckoutsTab.tsx
src/components/MyAccount/CheckoutsTab/RenewButton.tsx
src/components/MyAccount/RequestsTab/CancelButton.tsx
src/components/MyAccount/RequestsTab/FreezeButton.tsx
src/components/MyAccount/RequestsTab/RequestsTab.test.tsx
src/components/MyAccount/RequestsTab/RequestsTab.tsx
src/components/MyAccount/RequestsTab/UpdateLocation.tsx
src/components/MyAccount/Settings/PasswordChangeForm.tsx
src/components/MyAccount/Settings/PasswordModal.tsx

- JIRA ticket [SCC-4190](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4190)
- Add loading indicator for freeze and renewal flows
- add skeleton loader just for update location cell
- update location loading modal cancel button no longer closes the modal
- add skeleton loader in update pin/password modal
- update pin cancel button no longer closes the modal
These tests are time sensitive in a way that I don't think is possible to have unit tests. Running locally, I have seen all the loading states appear appropriately.
- loading modals no longer have functional close buttons, but the close/cancel buttons were confusing in the workflow anyway.
[SCC-4190]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

Scc 4190/loading feedback

---

src/components/Layout/Layout.tsx
src/utils/cookieUtils.ts

Fix for timed logout modal bug that was causing an extra minute to still be displayed. The modal displays -1:00 before logging out. I don't think it's a blocker, though.

math.floor minutes for timed logout

---

src/components/MyAccount/Settings/AccountSettingsButtons.tsx
src/components/MyAccount/Settings/AccountSettingsTab.tsx
src/components/MyAccount/TimedLogoutModal.tsx
src/utils/cookieUtils.ts
src/utils/utilsTests/cookieUtils.test.ts

these QA comments: 
- https://docs.google.com/document/d/1rx8pHljNYFhItXtpEjaKPB9MHtqTfdxeEs7Nw8QpEuM/edit#heading=h.2cttxp3f1v48
- https://docs.google.com/document/d/1rx8pHljNYFhItXtpEjaKPB9MHtqTfdxeEs7Nw8QpEuM/edit#heading=h.6cbe9vt5qn6x
- Ensures that focus does not jump to account settings button after using the arrows to navigate to the settings tab
- fix timer skipping 0:00 and showing -1:00 minutes left 
-

Account settings focus and -1 bug

---

src/components/MyAccount/CheckoutsTab/CheckoutsTab.test.tsx
src/components/MyAccount/CheckoutsTab/RenewButton.tsx
src/context/PatronDataContext.tsx
src/types/myAccountTypes.ts

- JIRA ticket [SCC-4207](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4207)
- Renewal success modal was showing stale due date. Updated the code so the modal doesn't open until the data has been refreshed.
Due to the annoying as heck nature of testing checkout renewals, I hacked it by hardcoding the response of `renewCheckout` in `/pages/api/account/helpers.ts` to return this body:
`{
"id": "https://nypl-sierra-test.nypl.org/iii/sierra-api/v6/patrons/checkouts/66527526",
"patron": "https://nypl-sierra-test.nypl.org/iii/sierra-api/v6/patrons/6742743",
"item": "https://nypl-sierra-test.nypl.org/iii/sierra-api/v6/items/38427966",
"barcode": "33333418738239",
"dueDate": "2024-08-20T08:00:00Z",
"callNumber": "B CLARE M",
"numberOfRenewals": 5,
"outDate": "2024-07-19T18:39:33Z", …

set modal props outside of fetch callback

---

src/components/MyAccount/RequestsTab/CancelButton.tsx
src/models/MyAccount.ts
src/models/modelTests/MyAccount.test.ts

- JIRA ticket [SCC-4212](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4212)
- Addresses bug where if there are only bib level holds, the requests construction errors.
unit tests and removing requests so there are only bib holds left and verifying that the requests still display.
-
[SCC-4212]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Scc 4212/bib holds only

---

CHANGELOG
pages/bib/[id]/all.tsx
pages/bib/[id]/index.tsx

- JIRA ticket [SCC-4187](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4187)
- Removes the useEffect that was initializing the client-side fetch on first render.
- Passes the view_all_item query param in the server side fetch in the /all page component.
- Tested locally, not sure if we need unit tests since server-rendering should be the default.
[SCC-4187]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4187 - Server render ItemTable

---

src/components/MyAccount/ProfileHeader.tsx
src/components/MyAccount/RequestsTab/RequestsTab.test.tsx
src/components/MyAccount/RequestsTab/UpdateLocation.tsx

- bug fix: clicking confirm location without updating the selection was leading to a hanging loading modal. Updated code to be more aware of whether the location was updated to avoid extraneous fetching and reference errors.
-

Noref my account final qa

---

.vscode/launch.json

- Launch profile for debugging Next apps in VSCode, very convenient way to inspect variables with breakpoints instead of using console.log.

Add launch profile for debugging in VSCode

---

CHANGELOG
src/components/ItemFilters/ItemFilters.tsx
src/components/ItemTable/RequestButtons.test.tsx
src/components/ItemTable/RequestButtons.tsx
src/components/Layout/Layout.tsx
src/models/Item.ts
src/models/modelTests/Item.test.ts

- JIRA ticket [SCC-4234](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4234)
- Fixes issues 3 and 4 from Clare's accessibility VQA doc. Added additional info about 1 & 2 in the ticket.
- Adds a getter to Item model for Request button titles that includes the volume if present.
- Adds a styling override to Layout.tsx that addresses the test wrapping on zoom.
- Added a unit test for the request button text
[SCC-4234]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4234 - VQA Accessibility Issues

---

CHANGELOG
__test__/fixtures/processedMyAccountData.ts
__test__/fixtures/rawSierraAccountData.ts
__test__/pages/account/account.test.tsx
src/components/MyAccount/ProfileHeader.tsx
src/models/MyAccount.ts
src/models/modelTests/MyAccount.test.ts
src/types/myAccountTypes.ts
src/utils/myAccountUtils.ts

- JIRA ticket [SCC-4233](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4233)
- Fetches username from sierra
- displays username
Updated unit tests and verified that usernames display. I don't have a patron account on hand with no username, so if anyone has one, that would be good to check!
-
[SCC-4233]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Scc 4233/add username to account header

---

CHANGELOG
src/utils/feedbackUtils.ts
src/utils/utilsTests/feedbackUtils.test.ts

- JIRA ticket [SCC-4230](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4230)
- Fixes a server-side error when posting to the feedback endpoint in the Next app, where null values in the metadata were unable to be parsed as json.
- This strips the null values on the server side, open to suggestions on where we should  be doing this.
- Added a unit test with a null value in the metadata
NA
[SCC-4230]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4230 - Filter out null values in feedback metadata

---

CHANGELOG
src/components/Layout/Layout.tsx

NA
- Removed gridColumnEnd that was added as an accessibility fix (turns out it wasn't necessary) to fix DRB sidebar right alignemnt

Hotfix - Fix layout grid styling

---

CHANGELOG
__test__/pages/bib/bibPage.test.tsx
discoveryApiResearchNowMapping.md
src/components/BibPage/ElectronicResources.test.tsx
src/components/BibPage/ElectronicResources.tsx
src/components/ItemFilters/ItemFilters.test.tsx
src/components/ItemFilters/ItemFilters.tsx
src/components/ItemTable/ItemAvailability.tsx
src/components/ItemTable/ItemTableCell.tsx
src/components/ItemTable/ItemTableControls.tsx
src/components/ItemTable/RequestButtons.test.tsx
src/components/ItemTable/RequestButtons.tsx
src/components/SearchResults/ElectronicResourcesLink.test.tsx
src/components/SearchResults/ElectronicResourcesLink.tsx
src/components/SearchResults/SearchResult.test.tsx
src/components/SearchResults/SearchResult.tsx
src/models/Bib.ts
src/models/BibDetails.ts
src/models/ItemTableData.ts
src/models/modelTests/BibDetails.test.ts
src/models/modelTests/SearchResultsBib.test.ts
src/utils/appUtils.ts
src/utils/utilsTests/appUtils.test.ts
styles/components/BibDetails.module.scss
styles/components/ItemTable.module.scss

- JIRA ticket [SCC-4235](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4235)
- Changes  copy to sentence case 
- Misc styling / copy tweaks from VQA doc
- Added a ItemTableCell component to allow styling the inner item table elements (programmatically rendering DS Text component in the ItemTableData model gave me problems with Typescript but there might be a solution)
- Note: the changes requested in the ticket for table heading and year button will be updated on the DS level
- Changed copy in a lot of tests
NA
[SCC-4235]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4235 - VQA Styling / Copy Fixes

---

src/components/SearchForm/SearchForm.tsx
src/utils/searchUtils.ts

- JIRA ticket [SCC-4260](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4260) and [SCC-4261](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4260)
- Adds call number search scope
- rearrange search options dropdown
- sentence cases search options labels
Running some full string and partial call number searches
-
[SCC-4260]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCC-4261]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Scc 4260/rename fields

---

CHANGELOG
pages/bib/[id]/all.tsx
pages/bib/[id]/index.tsx
src/config/constants.ts
src/server/api/bib.ts
src/server/api/tests/bib.test.ts
src/types/bibTypes.ts
src/utils/bibUtils.ts
src/utils/utilsTests/bibUtils.test.ts

- JIRA ticket [SCC-4287](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4287)
- Integrate view_all query param on client side
- Only call batched fetch when item filters are active
- Added TODO notes for changes to be made when filter params are supported by the all_items endpoint in discovery.
- Updated getBibQueryString unit tests and removed those specific to batched fetch.
- NA
[SCC-4287]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4287 - Incorporate View All Endpoint

---

CHANGELOG
src/utils/searchUtils.ts
src/utils/utilsTests/searchUtils.test.ts

- JIRA ticket [SCC-4277](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4277)
- Fixes a bug where the search results display string reads "Displaying x results for undefined" when there are no fields in the search query string.
- This scenario is reproducible by going to the search results page with only filters in the query string: https://www.nypl.org/research/research-catalog/search?filters[subjectLiteral]=Intellectual%20life
- Removed the redundant length check on displayStringArray since .join doesn't add a separator when the array length is 1.
- Added a unit test for this scenario
NA
[SCC-4277]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4277 - Fix undefined error on display string

---

CHANGELOG
src/components/ItemTable/ItemAvailability.tsx
src/components/ItemTable/ItemTable.tsx
styles/components/ItemTable.module.scss

- JIRA ticket [SCC-4264](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4264)
- Adds isScrollable to ItemTable on mobile
- Miscellaneous fixes to styling following DS version bump (padding, text-alignment, matching column headings to design)
- NA
[SCC-4264]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4264 - Small styling tweaks following DS version bump

---

CHANGELOG
src/components/BibPage/BibDetail.tsx
src/models/BibDetails.ts
src/models/modelTests/BibDetails.test.ts
src/types/bibDetailsTypes.ts

- JIRA ticket [SCC-4305](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4305)
- Fixes bug where the subject urls for "parent" subject elements are incorrect.
- Adds flattenSubjectHeadingUrls which iterates through subject heading's parent elements to build an array of subject heading urls.
- Simplifies buildSubjectHeadings
- Renames "Url" to BibDetailsURL. Wanted to make it more explicit since I was briefly tripped up by spelling it URL, which is built into Typescript.
- Renames constructSubjectHeadingsArray to constructSubjectLiteralsArray
- We had tests for this but they were faulty, fixed now.
- NA
[SCC-4305]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4305 - Fix incorrect subject heading urls bug

---

CHANGELOG
src/types/bibDetailsTypes.ts
src/utils/bibUtils.ts

- JIRA ticket [SCC-4308](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4308)
- Adds optional chaining to value in isRtl to prevent 500 error when a bib url is missing a label.
- Makes the url label optional in the BibDetailURL type.
- No tests existed for this function but this is a somewhat urgent fix so I'll open a ticket to add tests as a follow up.
- NA
[SCC-4308]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4308 - Fix error when bib detail url missing label

---

CHANGELOG
styles/components/ItemTable.module.scss

- JIRA ticket [SCC-4299](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4299)
- Updates CSS to make the Item Table widths the same in search results
NA
NA
[SCC-4299]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4299 - Fix Item widths on search results

---

CHANGELOG
src/models/Bib.ts
src/models/modelTests/SearchResultsBib.test.ts

NA - regarding bug reported during RC office hours.
This query https://www.nypl.org/research/research-catalog/search?q=*T-mss&search_scope=callnumber
Returns some bibs with no title, which was breaking the bib model construction. To ameliorate, I added optional chaining as well as a default of title display and clear fallback.
- updated unit tests for searchResultsBib model
-

add title default

---

__test__/fixtures/searchResultsManyBibs.ts
__test__/pages/search/advancedSearchForm.test.tsx
__test__/pages/search/searchResults.test.tsx
pages/search/advanced.tsx
src/components/ItemFilters/ActiveFilters.tsx
src/components/ItemFilters/ItemFilters.tsx
src/components/Layout/Layout.tsx
src/components/RefineSearch/CancelSubmitButtonGroup.tsx
src/components/RefineSearch/RefineSearch.test.tsx
src/components/RefineSearch/RefineSearch.tsx
src/components/RefineSearch/SearchFilterCheckboxField.tsx
src/components/SearchFilters/AppliedFilters.tsx
src/components/SearchFilters/DateForm.tsx
src/components/SearchForm/SearchForm.tsx
src/config/aggregations.ts
src/config/aggregations.tsx
src/models/SearchResultsFilters.ts
src/models/modelTests/SearchResultsFilters.test.ts
src/types/filterTypes.ts
src/types/searchTypes.ts
src/utils/advancedSearchUtils.ts
styles/components/Search.module.scss

- update location label names 
- display locations as single column
- all buttons in sentence case
- extract active filters tagset with header and use in search results and bib page
- move refine search panel buttons below advanced search button
- fix bug where clear filters was not removing location checkboxes
- misc spacing updates
- rm superfluous class names

QA and VQA for location filters

---

src/components/EDSBanner.tsx

- JIRA ticket [SCC-4365](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4365)
- updates the eds banner text
-
[SCC-4365]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update eds text

---

CHANGELOG
src/utils/appUtils.ts

Hotfix for analytics bug where page routes without a query string were emitting a homepage view event. This was caused by the use of a -1 ending index in a substring function, which returns an empty string.
This was missed in QA for the bib release page, and I assume we didn't notice it when we released the search results because most routes have a query string.
There are no unit tests for trackVirtualPageView since it has a void return type, but I'll separate this logic out to add unit tests as a fast-follow.

HOTFIX - Fix analytics page tracking events

---

.github/workflows/deploy_train.yml
pages/hold/confirmation/[id].tsx
pages/hold/request/[id]/index.tsx
src/server/api/hold.ts
src/types/holdPageTypes.ts

Draft PR for server-side Hold Confirmation functions. The getter functions are mostly done but they need to be integrated and tested.
TODO:
- Render ineligibility messages and set new status on Hold form pages
- Fetch item in confirmation page and show details

SCC-3762 - Hold Confirmation Server Functions

---

src/components/MyAccount/ProfileHeader.tsx
src/components/MyAccount/ProfileTabs.tsx
src/components/MyAccount/Settings/AccountSettingsTab.tsx
src/components/MyAccount/Settings/AddButton.tsx
src/components/MyAccount/Settings/EditButton.tsx
src/components/MyAccount/Settings/EmailForm.test.tsx
src/components/MyAccount/Settings/HomeLibraryForm.test.tsx
src/components/MyAccount/Settings/NotificationForm.test.tsx
src/components/MyAccount/Settings/PasswordForm.test.tsx
src/components/MyAccount/Settings/PasswordForm.tsx
src/components/MyAccount/Settings/PhoneForm.test.tsx
src/components/MyAccount/Settings/SaveCancelButtons.tsx
src/components/MyAccount/Settings/SettingsInputForm.tsx
src/components/MyAccount/Settings/SettingsLabel.tsx
src/components/MyAccount/Settings/SettingsSelectForm.tsx
src/components/MyAccount/Settings/StatusBanner.tsx
src/components/MyAccount/Settings/UsernameForm.test.tsx
src/components/MyAccount/Settings/UsernameForm.tsx

- JIRA ticket [SCC-4384](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4384)
- Addresses comments in [My Account 2.0](https://docs.google.com/document/d/1Rwi0eSEVBEfAMK1ypQ0NkGNd3FtI0ngRAaD-ONPIEvo/edit?tab=t.0) VQA and accessibility review
- Mainly spacing (VQA) and focus behavior (a11y)
On mobile when you click edit for Home library/ Notification preference/Password, the fields jump up slightly like they're losing padding/margin or height is just not the same between the two states. I would love a fresh pair of eyes on this since I'm having trouble tracking down why this is happening
- Adds focus management to all form fields
[SCC-4384]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

SCC-4384: My Account 2.0 VQA/a11y round 1

---

src/components/HoldPages/CopyrightRestrictionsBanner.tsx
src/components/HoldPages/EDDRequestForm.tsx
src/components/HoldPages/HoldConfirmationAccordionData.tsx
src/components/HoldPages/HoldConfirmationFAQ.tsx
src/config/constants.ts

- JIRA ticket [SCC-4380](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4380)
- Small VQA fixes
[SCC-4380]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4380 - Hold page VQA fixes

---

src/components/MyAccount/Settings/AddButton.tsx
src/components/MyAccount/Settings/EditButton.tsx
src/components/MyAccount/Settings/EmailForm.test.tsx
src/components/MyAccount/Settings/NotificationForm.test.tsx
src/components/MyAccount/Settings/PhoneForm.test.tsx
src/components/MyAccount/Settings/SettingsInputForm.tsx
src/components/MyAccount/Settings/SettingsSelectForm.tsx
src/components/MyAccount/Settings/StatusBanner.test.tsx
src/components/MyAccount/Settings/UsernameForm.tsx

- JIRA ticket [SCC-4389](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4389)
Resolves the following issues:
a11y: 
- When activating an Edit button, when there are multiple fields focus is moving to the last one when it seems more logical to move to the first
- Each phone/email label should be named uniquely - if one is primary, include that in the label, and then you could increment the labels for additional items. Do the same for trash labels.
QA:
- Add email button should display for accounts with no email
- Notification preference dropdown should disable phone or email as options if you don’t have them **
- Notification preference “Edit” button should be disabled if you don’t have phone or email to change it to, and display a banner with “Please set a phone number or email …

SCC-4389: My Account 2.0 QA round 1 and VQA/a11y round 2

---

src/components/MyAccount/Settings/PasswordForm.tsx
src/components/MyAccount/Settings/SettingsSelectForm.tsx

- JIRA ticket [SCC-4409](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4409)
QA:
- When you click “Edit” after canceling a filled out password form, it allows the “Save Changes” button to be active even though the form is not currently valid. Resolve
VQA:
- Info banner for None state needs to match width of the banner for username
The banner width update can only be seen on an account that has no attached phone number or email, and has its notification preference set to None. Use this one: 25555001351471 / 1082 but DO NOT actually Save Changes on an email/phone or on the notification preference :)
To test the password form, submit an incorrect password OR fill out the whole form correctly then click Cancel. When you reopen the form, the Save Changes button should be disabled. …

SCC-4409: My Account 2.0 QA #3

---

pages/hold/request/[id]/edd.tsx
pages/hold/request/[id]/index.tsx
src/models/Item.ts
src/models/modelTests/Item.test.ts
src/utils/appUtils.ts

- JIRA ticket [SCC-4428 ](url)
- We had missed a small bit of functionality on DFE that converts the source to kebab case before being sent in hold request params.
- Added a unit test
- NA

SCC-4428 - Pass item source in kebab case to hold forms

---

CHANGELOG
__test__/pages/hold/eddRequestPage.test.tsx
__test__/pages/hold/holdRequestPage.test.tsx
pages/hold/request/[id]/edd.tsx
pages/hold/request/[id]/index.tsx
src/components/HoldPages/EDDRequestForm.tsx
src/components/HoldPages/HoldContactButton.tsx
src/components/HoldPages/HoldRequestErrorBanner.tsx
src/components/HoldPages/HoldRequestForm.tsx
src/components/HoldPages/PatronIneligibilityErrors.tsx
src/utils/holdPageUtils.ts

- JIRA ticket [SCC-4427](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4427)
- Updates error banner copy, styles, and adds HoldContactButton component for ease of re-use.
- Only renders ineligibility reasons as a List when more than one (Apoorva request not in the VQA doc)
- Disables the Submit button when the patron is ineligible to place holds.
- Misc styling changes on hold request forms
- Remove isRequired from EDD form fields to prevent chrome's native handling of focus on errors.
- Updated unit tests
- NA
[SCC-4427]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4427 - VQA Round 2 Fixes

---

__test__/pages/bib/bibPage.test.tsx
package-lock.json
package.json
src/components/MyAccount/Settings/PasswordForm.tsx
src/components/MyAccount/Settings/SettingsInputForm.tsx
src/components/MyAccount/Settings/SettingsSelectForm.tsx
src/components/MyAccount/Settings/UsernameForm.tsx

- JIRA ticket [SCC-4409](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4409)
- Updates DS version to `3.5.1`
- Restores `isClearable` functionality to input fields
VQA:
- Info banner moved up 8px
The banner update can only be seen on an account that has no attached phone number or email, and has its notification preference set to None. Use this one: 25555001351471 / 1082 
To test `isClearable`, just clear any field to ensure the focus stays on that field
[SCC-4409]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

My Account 2.0 QA round 4

---

CHANGELOG
__test__/pages/hold/eddRequestPage.test.tsx
pages/api/hold/request/[id]/edd.ts
pages/api/hold/request/[id]/index.ts
pages/hold/request/[id]/edd.tsx
src/components/HoldPages/EDDRequestForm.tsx
src/server/api/hold.ts
src/utils/holdPageUtils.ts
src/utils/utilsTests/holdPageUtils.test.ts

- JIRA ticket [SCC-4405](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4405)
- Adds server-side validation on EDD hold requests
- Fixes bugs causing errors on No-js hold requests (related to JSON parsing/query string formatting)
- Adds formState and validatedFields query params to populate field values/validation state on refreshes/js-disabled redirects.
- Renames initialEDDInvalidFields to defaultValidatedEDDFields
- Added unit tests
- I thought about adding autofocus when js is disabled but it ended up adding a bunch of code, so not sure if it's worth it. Let me know if you think this is important (will check with Clare as well) and I'll add it back.
[SCC-4405]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

Scc 4405/hold pages js disabled

---

pages/api/hold/request/[id]/index.ts

This is a small bug fix for an issue I introduced in the no-js work that leads to a server error on on-site hold requests.
This PR adds a ternary (present in the edd route) that checks if the request body is stringified, which it isn't in the case of no-js.

HOTFIX - On-site hold bug fix

---

CHANGELOG
src/components/Links/ExternalLink/ExternalLink.tsx
src/server/api/search.ts
src/server/nyplApiClient/index.ts

Hotfix for a bug on production where no results are appearing in the DRB sidebar.
This was introduced in the latest My Account release with the implicit setting of the "v0.1" suffix to all urls passed to the api client. My fix addresses this by allowing the passing of an empty version as a temporary solution.
I added a TODO to revisit this later.

HOTFIX - No results in DRB sidebar

---

pages/api/hold/request/[id]/edd.ts

- JIRA ticket [SCC-4460](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4460)
- Fixes a bug where the item id was getting overridden by the edd params at the time of the post request.
- No tests but I'll open a ticket to revisit adding test coverage to API routes as a follow-up.
- NA
[SCC-4460]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Item id not getting passed at time of EDD hold post

---

CHANGELOG
__test__/pages/hold/eddRequestPage.test.tsx
__test__/pages/hold/holdRequestPage.test.tsx
pages/api/hold/request/[id]/edd.ts
pages/api/hold/request/[id]/index.ts
pages/hold/request/[id]/edd.tsx
pages/hold/request/[id]/index.tsx

- JIRA ticket [SCC-4462](https://newyorkpubliclibrary.atlassian.net/browse/SCC-SCC-4462)
- Adds patron authentication to hold api routes (returning a 403 status)
- Handles the error on the client side by setting an invalid status if a 403 status is returned.
- Added unit tests.
- NA
[SCC-4462]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4462 - Add patron authentication to Hold API routes

---

CHANGELOG
__test__/pages/bib/bibPage.test.tsx
src/components/ItemTable/ItemTableControls.tsx

This hotfix resolves an issue where the "View All" loading text is being rendered twice on the Bib page on production. The issue arose due to a recent change in the design system, which led to the label component being rendered twice.
Changes Made:
- Removed the duplicate label component that was being rendered, ensuring the "View All" loading text is only displayed once.
- Styled the ProgressIndicator component to match the previous design, ensuring visual consistency with the old styles.

Hotfix for Duplicated "View All" Loading Text on the Bib Page

---

src/models/Bib.ts

we expected supplementary content to have labels and they don't always. heres a hotfix.

optional chaining on supp content

---

CHANGELOG
pages/hold/confirmation/[id].tsx
pages/hold/request/[id]/index.tsx
src/config/constants.ts
src/models/Item.ts
src/utils/itemUtils.ts

This PR addresses an issue that was identified after the launch of the Hold pages, where certain off-site partner records were showing an error on the hold request page.
The issue occurred because the delivery location fetch was failing. This was due to missing functionality in DFE, where barcodes are extracted from the identifier field for bibs with legacy formatting.
This PR adds the necessary functionality to resolve the issue. I've also opened a [follow-up ticket](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4474) to refactor the solution and add unit tests.

HOTFIX: Resolve delivery location fetch issue for off-site items with legacy barcode identifiers

---

src/server/api/hold.ts
src/server/api/tests/hold.test.ts

Fixes another location bug visible in on this [item request page](https://www.nypl.org/research/research-catalog/hold/request/pb994935823506421-pi23660840550006421)
This is happening because Discovery API is returning some staff-only locations, which should be filtered out.

Filter out null locations in delivery location fetch result

---

CHANGELOG
__test__/pages/search/advancedSearchForm.test.tsx
pages/search/advanced.tsx
pages/search/index.tsx

- JIRA ticket [SCC-4345](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4345)
- Add searched_from=advanced param to searches from advanced search
- resets upon a new search from the search bar.
- persists on pagination updates, as well on refine search updates
Updating local tests to include the param, and manual testing on local.nypl.org
- NA
[SCC-4345]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add advanced search param

---

src/models/MyAccount.ts

- JIRA ticket [SCC-4610](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4610)
- Changes `format` back to `recordType` in the `fetchHolds` call in MyAccount (was changed to `format` in a search-and-replace [here](https://github.com/NYPL/research-catalog/commit/49493e1234c1844c6c04fd2e008bc73898ecf4b2))
* This is what the path used to be, and tests are passing.
- N/A
- [N/A] I updated the CHANGELOG with the appropriate information and JIRA ticket number (if applicable).
- [N/A] I have added relevant accessibility documentation for this pull request.
[SCC-4610]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SCC-4610] format->recordType for MyAccount requests tab

---

CHANGELOG
src/server/sierraClient/index.ts

- JIRA ticket [SCC-4627](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4627)
- Sets `wrapper.post` instead of `wrapper.get` in the Sierra client wrapper so that the call to `patrons/validate` (needed to reset the password) works as expected
- ** Not urgent imo but want to note that we mock all of our requests (see `helpers.test.tsx`), so that the wrong request method wasn't, and would never be, caught. Wondering if we should revisit these tests although I know they gave us lots of grief the first time around
[SCC-4627]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4627: Sierra wrapper POST correction

---

CHANGELOG
src/components/SearchForm/SearchForm.tsx

- JIRA ticket [SCC-4601](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4601)
- Removes the `zIndex` styling that was causing keyword dropdown arrow icon to disappear on click
[SCC-4601]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4601: Keyword dropdown icon z index

---

__test__/fixtures/bibFixtures.ts
pages/bib/[id]/index.tsx
src/components/BibPage/BibDetail.test.tsx
src/components/BibPage/ElectronicResources.test.tsx
src/components/BibPage/ElectronicResources.tsx
src/components/BibPage/FindingAid.test.tsx
src/components/BibPage/FindingAid.tsx
src/components/Layout/Layout.tsx
src/components/SearchResults/ElectronicResourcesLink.tsx
src/components/SearchResults/SearchResult.tsx
src/models/Bib.ts
src/models/BibDetails.ts
src/models/modelTests/Bib.test.ts
src/models/modelTests/BibDetails.test.ts
src/utils/bibUtils.ts

- JIRA ticket [SCC-4105](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4105)
- Creates `FindingAid` component and adds it to search results and bib page
- Adjusts `ElectronicResource` (bib page) and `ElectronicResourceLink` (search result) styling
- Updates `BibDetails` model to filter the finding aid out of `topDetails`' `supplementaryContent` where necessary
- Adds standalone `findingAid` property to `BibDetails`
- Adds `getFindingAidFromSupplementaryContent` to `bibUtils`, used for both `BibDetails` and `Bib` model
[SCC-4105]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4105: Finding aid links

---

CHANGELOG
pages/hold/request/[id]/edd.tsx
pages/hold/request/[id]/index.tsx
src/components/HoldPages/EDDRequestForm.tsx
src/types/global.d.ts

- JIRA ticket [SCC-4649](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4649)
- Adds global window type so that clientside components can access `window.dataLayer`
- Adds event to EDD request and on site hold request forms (on successful submission)
- Needs to be tested in Google Tag Manager
[SCC-4649]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4649: GA events for catalog requests

---

pages/search/index.tsx
src/components/AppliedFilters/AppliedFilters.tsx
src/components/SearchFilters/SearchFilterModal.tsx
src/components/SearchFilters/SearchFilters.tsx
src/components/SearchForm/SearchForm.tsx
src/context/FocusContext.tsx

Optimize might be optimistic... This pr does the following:
- refactor change handlers on the multiselect so the query update happens after applied filters are updated
- I'm no longer seeing chrome reporting any violation for the click handler, which was once reporting at >1000ms 
- Not really necessary, but I thought that it might be a slightly easier flow if the `FocusContext` was responsible for the focus state and for refocusing upon page rerender/reload. This might require some more involved QA, but as far as I can see, this update maintains the focus requirements. I would advocate for this approach because it can help us remove some more of the components' knowledge of focus logic. 
I was sporadically seeing some "update depth maximum reached" warnings in the console, but not …

Noref optimize filters

---

CHANGELOG
pages/bib/[id]/index.tsx
src/utils/bibUtils.ts
src/utils/utilsTests/bibUtils.test.ts

- JIRA ticket [SCC-4749](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4749)
- Adds the bib title (truncated if necessary so that entire string is <= 100 characters) to the tab title on the bib page
- Tests
- Already cleared by Clare
[SCC-4749]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4749: Add bib title to tab

---

CHANGELOG
src/components/BibPage/BibDetail.test.tsx
src/models/BibDetails.ts

- JIRA ticket [SCC-4771](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4771)
- Adds language back into the resource fields that we display in`bottomDetails` for `BibDetails` (probably missed in the migration to DFE)
[SCC-4771]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4771: Language display bug

---

CHANGELOG
__test__/pages/_error/_error.test.tsx
pages/_error.tsx
pages/testError.tsx

- JIRA ticket [SCC-4787](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4787)
- Creates the custom error page for uncaught server/client errors that are not 404s
- Creates a test error page which throws an error
- Unit tests for the error page
- Locally, you can uncomment one of the three potential errors in `testError.tsx`, then build and run the app in production mode (`npm run build`, `npm run start`), and go to `localhost:3000/research/research-catalog/testError` ) to see the app catch the error
- If you do this with `npm run dev` it'll just show you the Next overlay with the error because it assumes you want to resolve it :)
[SCC-4787]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

SCC-4787: General error page

---

CHANGELOG
jest.setup.js
pages/404/index.tsx
pages/_error.tsx
pages/api/feedback-rc.ts
src/components/FeedbackForm/FeedbackForm.test.tsx
src/components/FeedbackForm/FeedbackForm.tsx
src/components/SearchResults/SearchError.tsx
src/context/FeedbackContext.tsx
src/types/feedbackTypes.ts

- JIRA ticket [SCC-4776](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4776)
- Adds `requestedURL` to the `FeedbackContext` and updates `onOpen` to get the current URL before opening the feedback box
- Adds `openFeedbackFormWithError` to all error pages "contact us" links which just sets the error to true before opening the feedback box --> adds notification text to the feedback box if "contact us" from an error page is what opened it
[SCC-4776]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4776: Add requested URL to feedback data

---

__test__/pages/hold/confirmation.test.tsx
__test__/pages/hold/eddRequestPage.test.tsx
__test__/pages/hold/holdRequestPage.test.tsx
pages/hold/confirmation/[id].tsx
pages/hold/request/[id]/edd.tsx
pages/hold/request/[id]/index.tsx

- Follows up on JIRA ticket [SCC-3360](https://newyorkpubliclibrary.atlassian.net/browse/SCC-3360)
- Adds the item ID to the session storage item key, so that the check is specific to the hold you just made rather than just any hold 
- Updated unit tests to reflect
- Make a hold. Then go immediately make another hold on a different item, go back, you should not see the banner
[SCC-3360]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-3360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bug fix: Adding hold ID to hold completed check

---

CHANGELOG
__test__/pages/browse/index.test.tsx
pages/api/browse.ts
pages/browse/index.tsx
src/config/constants.ts
src/server/api/browse.ts
src/server/api/tests/browse.test.ts
src/types/browseTypes.ts
src/utils/browseUtils.ts

- JIRA ticket [SCC-4774](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4774)
- Adds the serverside fetcher `fetchSubjects`– used in `getServerSideProps` on the browse index page
- For POC, this currently calls `fetchSubjects({ q: "" })` on `browse/index`, you can log it to see the output
- Also adds the clientside browse route handler (`api/browse`) which just passes params to `fetchSubjects`
- Adds a bunch of types and helper functions for the parsing of browse params
- There are separate tickets for sort and pagination, so those will be refined and tested further once they have their corresponding page controls
- Noting again for posterity that the `DISCOVERY_BROWSE_ROUTE` = `/discovery/browse/subjects` for now, and all "browse"-named things really just refer to subject …

SCC-4774: Browse API handler

---

CHANGELOG
src/components/BibPage/FindingAid.test.tsx
src/components/BibPage/FindingAid.tsx

- JIRA ticket [SCC-4803](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4803)
- Updates finding aid link and copy, and corresponding unit test
- It seems like LibGuides is adding GA params to the URL... will confirm with Sean/Nora
Search something with a finding aid and click the link!
[SCC-4803]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4803: Update Finding aid link and copy

---

CHANGELOG
pages/browse/index.tsx
src/components/Banners/SubjectHeadingBanner.tsx
src/components/Layout/Layout.tsx
src/components/SearchResults/ResultsSort.tsx
src/config/constants.ts
src/utils/utilsTests/browseUtils.test.ts

- JIRA ticket [SCC-4572](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4572)
- Adds `Pagination` to browse index page
Advance through the pages . Of the browse index
[SCC-4572]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4572: Browse index pagination

---

CHANGELOG
__test__/pages/bib/bibPage.test.tsx
src/components/BibPage/BibDetail.test.tsx
src/models/BibDetails.ts

- JIRA ticket [SCC-4763](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4763)
- We already remove annotated MARC fields with matching labels, this also removes fields that match any *value* in the bib
- Logs when there's a unique MARC value that we keep (so we can see what bibs are missing over time)
- This seems like it's really gonna clutter the logs but the log was specifically requested
Check that there's no repeated labels, or repeated values, in the details of a bib page. 
For example: 
[Prod bib with duplicates](https://www.nypl.org/research/research-catalog/bib/b22811365)
[Same bib on Vercel with duplicates removed](https://research-catalog-git-scc-4763-remove-duplicate-marc-fields-nypl.vercel.app/research/research-catalog/bib/b22811365)
- The annotated MARC fields `Title`, …

SCC-4763: Remove duplicated MARC values from bib details

---

pages/bib/[id]/index.tsx
src/models/BibDetails.ts
src/types/bibDetailsTypes.ts

- JIRA ticket [SCC-4763](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4763)
- Updates the workings of the `BibDetails` model so that the MARC tags are passed through, and adds all MARC tags to the log of a given annotated MARC field that's being kept
- Involves adding `MarcDetail` and `MarcLinkedDetail` types just to keep everything all lined up
- Reformats log, and now includes recent updates to the logger
[SCC-4763]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4763: Duplicate AM fields formatting edition

---

CHANGELOG
playwright/pages/search_page.ts
playwright/tests/Search/search_keyword.spec.ts

- JIRA ticket [4844](https://newyorkpubliclibrary.atlassian.net/browse/SCC-{4844})
- adds Playwright test for keyword search on RC
tests pass locally.
-
- [x ] I updated the CHANGELOG with the appropriate information and JIRA ticket number (if applicable).
- [ x] All new and existing tests passed.

Scc 4844/playwright keyword search

---

CHANGELOG
__test__/pages/404/404.test.tsx
pages/404/redirect.tsx

- JIRA ticket [SCC-4876](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4876)
- Updates the `404/redirect` page to also use our new error layout, and correct copy
Hit `/research/research-catalog/404/redirect` and confirm it looks like our other 404 page, only with links back to circulating and legacy
[SCC-4876]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4876: Update redirect 404 page

---

CHANGELOG
__test__/pages/bib/bibPage.test.tsx
src/components/BibPage/BibDetail.test.tsx
src/components/BibPage/FindingAid.tsx
src/components/ItemFilters/ItemFilters.test.tsx
src/components/ItemFilters/ItemFilters.tsx
src/components/ItemTable/ItemTable.tsx
src/components/SearchResults/ElectronicResourcesLink.tsx
src/components/SearchResults/SearchResult.tsx
src/components/SearchResults/SearchResultItems.tsx
src/config/constants.ts
src/models/BibDetails.ts
src/models/ItemTableData.ts
src/types/filterTypes.ts
src/utils/itemFilterUtils.ts
src/utils/utilsTests/bibUtils.test.ts
src/utils/utilsTests/itemFilterUtils.test.tsx
styles/components/ItemTable.module.scss

- JIRA ticket [SCC-4905](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4905)
- Removes format column from item table on bib page, moves it to bib-level top details
- Removes format from search result card and replaces the item table component with a custom table (departs from DS since rows were required)
- Removes item format from tests and types relating to bib page
[SCC-4905]: https://newyorkpubliclibrary.atlassian.net/browse/SCC-4905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCC-4905: Remove item format display

---

CHANGELOG
playwright/tests/Search/search_subject.spec.ts

- JIRA ticket [4857](https://newyorkpubliclibrary.atlassian.net/browse/SCC-4857)
-- Adds Playwright test for subject search.
-- all tests pass locally
-

added playwright subject search test
